version: "2.2"
services:
  {{ cookiecutter.project_slug }}:
    container_name: {{ cookiecutter.project_slug }}
    entrypoint: npm start
    ports:
      - 3000:3000
    build: .
    environment:
      - BOT_USER_OAUTH_ACCESS_TOKEN
      - APP_TOKEN
